vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        biens_images:
            uri_prefix: '%images_directory%'
            upload_destination: '%images_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
